INSERT INTO GENERAL_PROFILE (ID, TYPE_OF_DEVICE, CONSUMPTION_RANGE, AVERAGE_HOURLY_CONSUMPTION, INSTANTANEOUS_CONSUMPTION) VALUES('1', 'Very large appliance', '4', '6', '5.5' );
INSERT INTO GENERAL_PROFILE (ID, TYPE_OF_DEVICE, CONSUMPTION_RANGE, AVERAGE_HOURLY_CONSUMPTION, INSTANTANEOUS_CONSUMPTION) VALUES('2', 'Large appliance', '3', '5', '4.5' );
INSERT INTO GENERAL_PROFILE (ID, TYPE_OF_DEVICE, CONSUMPTION_RANGE, AVERAGE_HOURLY_CONSUMPTION, INSTANTANEOUS_CONSUMPTION) VALUES('3', 'Medium appliance', '3', '4', '3.5' );
INSERT INTO GENERAL_PROFILE (ID, TYPE_OF_DEVICE, CONSUMPTION_RANGE, AVERAGE_HOURLY_CONSUMPTION, INSTANTANEOUS_CONSUMPTION) VALUES('4', 'Small appliance', '2', '3', '2.5' );
INSERT INTO GENERAL_PROFILE (ID, TYPE_OF_DEVICE, CONSUMPTION_RANGE, AVERAGE_HOURLY_CONSUMPTION, INSTANTANEOUS_CONSUMPTION) VALUES('5', 'Very small appliance', '1', '2', '1.5' );
