INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (1, '356AC37692', 'Toaster');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (2, '6538B2349D', 'Laptop');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (3, '845A3F5673', 'Kettle');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (4, '761239DCF1', 'Television');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (5, '628D23A853', 'Computer');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (6, '3849C32683', 'Light');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (7, '22568A5638', 'Phone Charger');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (8, '7538632468', 'Vaccum');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (9, 'AA3578B34F', 'Radio');
INSERT INTO `cerberus`.`rfid_tag` (`ID`, `NUMBER`, `DESCRIPTION`) VALUES (10, '479A347B31', 'Alarm Clock');
