INSERT INTO USER_TYPE (ID, TYPE_NAME) VALUES(1, 'System Administrator' );
INSERT INTO USER_TYPE (ID, TYPE_NAME) VALUES(2, 'System Owner' );
INSERT INTO USER_TYPE (ID, TYPE_NAME) VALUES(3, 'Consumer' );
