SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `Cerberus` ;
CREATE SCHEMA IF NOT EXISTS `Cerberus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Cerberus` ;

-- -----------------------------------------------------
-- Table `Cerberus`.`PERSONAL_INFORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`PERSONAL_INFORMATION` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`PERSONAL_INFORMATION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `FIRST_NAME` TINYTEXT NULL ,
  `LAST_NAME` TINYTEXT NULL ,
  `PHONE_NUMBER` TINYTEXT NULL ,
  `ADDRESS` TEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`LOGIN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`LOGIN` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`LOGIN` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `USERNAME` TINYTEXT NULL ,
  `PASSWORD_VAL` TINYTEXT NULL ,
  `CREATED_DATE` DATE NULL ,
  `CREATED_USER_ID` INT(11) NULL ,
  `LAST_UPDATED_DATE` DATE NULL ,
  `LAST_UPDATED_USER_ID` INT(11) NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`USER_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`USER_TYPE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`USER_TYPE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `TYPE_NAME` TINYTEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`USER_SETTING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`USER_SETTING` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`USER_SETTING` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `DEFAULT_OPERATION` INT(11) NULL ,
  `DEFAULT_ASSIGNMENT` INT(11) NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`USERS` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`USERS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `USER_SETTING_ID` INT(11) NULL ,
  `USER_TYPE_ID` INT(11) NOT NULL ,
  `LOGIN_ID` INT(11) NOT NULL ,
  `PERSONAL_INFORMATION_ID` INT(11) NOT NULL ,
  `CREATED_DATE` DATE NULL ,
  `CREATED_USER_ID` INT(11) NULL ,
  `LAST_UPDATED_DATE` DATE NULL ,
  `LAST_UPDATED_USER_ID` INT(11) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `USER_TABLE_FKIndex1` (`PERSONAL_INFORMATION_ID` ASC) ,
  INDEX `USER_TABLE_FKIndex2` (`LOGIN_ID` ASC) ,
  INDEX `USER_TABLE_FKIndex3` (`USER_TYPE_ID` ASC) ,
  INDEX `USER_TABLE_FKIndex4` (`USER_SETTING_ID` ASC) ,
  CONSTRAINT `fk_{4D9BD4AC-9A1F-4DB6-9E8A-9CB2C2ACBDF7}`
    FOREIGN KEY (`PERSONAL_INFORMATION_ID` )
    REFERENCES `Cerberus`.`PERSONAL_INFORMATION` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{F5F29746-0833-41D8-AB8D-D2F76D6888A2}`
    FOREIGN KEY (`LOGIN_ID` )
    REFERENCES `Cerberus`.`LOGIN` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{46C82E7A-345E-48BB-9ED4-648E3F3405AD}`
    FOREIGN KEY (`USER_TYPE_ID` )
    REFERENCES `Cerberus`.`USER_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{15088E1B-AC75-4136-BE48-8B120B01B952}`
    FOREIGN KEY (`USER_SETTING_ID` )
    REFERENCES `Cerberus`.`USER_SETTING` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`ROOM_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`ROOM_TYPE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`ROOM_TYPE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NAME` TINYTEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`ROOM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`ROOM` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`ROOM` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `ROOM_TYPE_ID` INT(11) NOT NULL ,
  `NAME` TINYTEXT NULL ,
  PRIMARY KEY (`ID`, `ROOM_TYPE_ID`) ,
  INDEX `ROOM_FKIndex1` (`ROOM_TYPE_ID` ASC) ,
  CONSTRAINT `fk_{57C41637-4A56-4C24-8C6A-7B99B6CD9BB1}`
    FOREIGN KEY (`ROOM_TYPE_ID` )
    REFERENCES `Cerberus`.`ROOM_TYPE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`OUTLET_OPERATION_MODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`OUTLET_OPERATION_MODE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`OUTLET_OPERATION_MODE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NAME` TINYTEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`OUTLET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`OUTLET` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`OUTLET` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `OUTLET_OPERATION_MODE_ID` INT(11) NOT NULL ,
  `ROOM_ID` INT(11) NOT NULL ,
  `SERIAL_NUM` TINYTEXT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `OUTLET_FKIndex1` (`ROOM_ID` ASC) ,
  INDEX `OUTLET_FKIndex2` (`OUTLET_OPERATION_MODE_ID` ASC) ,
  CONSTRAINT `fk_{63AA46EC-AF1C-4006-86C3-726864F1DC65}`
    FOREIGN KEY (`ROOM_ID` )
    REFERENCES `Cerberus`.`ROOM` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{E5461FC8-5077-4C52-853B-F22D3C58FE98}`
    FOREIGN KEY (`OUTLET_OPERATION_MODE_ID` )
    REFERENCES `Cerberus`.`OUTLET_OPERATION_MODE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SOCKET_OPERATION_MODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SOCKET_OPERATION_MODE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SOCKET_OPERATION_MODE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `OUTLET_OPERATION_MODE` INT(11) NULL ,
  `DESCRIPTION` TEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SOCKET_OPERATION_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SOCKET_OPERATION_STATUS` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SOCKET_OPERATION_STATUS` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `STATUS_VALUE` TEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SOCKET`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SOCKET` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SOCKET` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `SOCKET_OPERATION_STATUS_ID` INT(11) NOT NULL ,
  `SOCKET_OPERATION_MODE_ID` INT(11) NOT NULL ,
  `OUTLET_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SOCKET_FKIndex1` (`OUTLET_ID` ASC) ,
  INDEX `SOCKET_FKIndex2` (`SOCKET_OPERATION_MODE_ID` ASC) ,
  INDEX `SOCKET_FKIndex3` (`SOCKET_OPERATION_STATUS_ID` ASC) ,
  CONSTRAINT `fk_{F61548DC-550F-4EC3-AC6C-5D3F97DA104C}`
    FOREIGN KEY (`OUTLET_ID` )
    REFERENCES `Cerberus`.`OUTLET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{42C4695B-2ECA-4B8F-9A9C-0B6AC6BB5B03}`
    FOREIGN KEY (`SOCKET_OPERATION_MODE_ID` )
    REFERENCES `Cerberus`.`SOCKET_OPERATION_MODE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{E5A5CFB9-41A8-4166-A790-47FA4AEB7303}`
    FOREIGN KEY (`SOCKET_OPERATION_STATUS_ID` )
    REFERENCES `Cerberus`.`SOCKET_OPERATION_STATUS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SCHEDULE_START_MODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SCHEDULE_START_MODE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SCHEDULE_START_MODE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `SOCKET_OPERATION_MODE_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SCHEDULE_START_MODE_FKIndex1` (`SOCKET_OPERATION_MODE_ID` ASC) ,
  CONSTRAINT `fk_{7E3A34D7-58D7-4D66-9717-4B01DDEC431B}`
    FOREIGN KEY (`SOCKET_OPERATION_MODE_ID` )
    REFERENCES `Cerberus`.`SOCKET_OPERATION_MODE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SCHEDULE_END_MODE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SCHEDULE_END_MODE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SCHEDULE_END_MODE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `SOCKET_OPERATION_MODE_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SCHEDULE_END_MODE_FKIndex1` (`SOCKET_OPERATION_MODE_ID` ASC) ,
  CONSTRAINT `fk_{EDE32FA4-0D2A-4AA0-AAD5-F117E91A7CAC}`
    FOREIGN KEY (`SOCKET_OPERATION_MODE_ID` )
    REFERENCES `Cerberus`.`SOCKET_OPERATION_MODE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SCHEDULED_EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SCHEDULED_EVENT` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SCHEDULED_EVENT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `SCHEDULE_END_MODE_ID` INT(11) NOT NULL ,
  `SCHEDULE_START_MODE_ID` INT(11) NOT NULL ,
  `SOCKET_ID` INT(11) NOT NULL ,
  `USERS_ID` INT(11) NOT NULL ,
  `START_TIME` TIME NULL ,
  `END_TIME` TIME NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SCHEDULED_EVENT_FKIndex1` (`USERS_ID` ASC) ,
  INDEX `SCHEDULED_EVENT_FKIndex2` (`SOCKET_ID` ASC) ,
  INDEX `SCHEDULED_EVENT_FKIndex3` (`SCHEDULE_START_MODE_ID` ASC) ,
  INDEX `SCHEDULED_EVENT_FKIndex4` (`SCHEDULE_END_MODE_ID` ASC) ,
  CONSTRAINT `fk_{0A5185F2-CAED-41C8-9B0A-6E94C01D710B}`
    FOREIGN KEY (`USERS_ID` )
    REFERENCES `Cerberus`.`USERS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{C343C72D-38FA-408C-AFF7-D7F371EDABC7}`
    FOREIGN KEY (`SOCKET_ID` )
    REFERENCES `Cerberus`.`SOCKET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{2E6ACAC5-E156-416D-A13F-735E87ADB060}`
    FOREIGN KEY (`SCHEDULE_START_MODE_ID` )
    REFERENCES `Cerberus`.`SCHEDULE_START_MODE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{1D49F5A7-D149-4ACB-9C8D-B8DE2C97CA6A}`
    FOREIGN KEY (`SCHEDULE_END_MODE_ID` )
    REFERENCES `Cerberus`.`SCHEDULE_END_MODE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SOCKET_ASSIGNMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SOCKET_ASSIGNMENT` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SOCKET_ASSIGNMENT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `SOCKET_ID` INT(11) NOT NULL ,
  `USERS_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `ASSIGNMENTS_FKIndex1` (`USERS_ID` ASC) ,
  INDEX `ASSIGNMENTS_FKIndex2` (`SOCKET_ID` ASC) ,
  CONSTRAINT `fk_{4A324159-B8D3-45F2-8F72-05686A4C6CA3}`
    FOREIGN KEY (`USERS_ID` )
    REFERENCES `Cerberus`.`USERS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{23BD712B-7922-4593-BB1D-63D9BB7EE508}`
    FOREIGN KEY (`SOCKET_ID` )
    REFERENCES `Cerberus`.`SOCKET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`RFID_TAG`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`RFID_TAG` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`RFID_TAG` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NUMBER` INT(11) NULL ,
  `DESCRIPTION` TEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`RFID_AUTHENTICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`RFID_AUTHENTICATION` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`RFID_AUTHENTICATION` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `RFID_TAG_ID` INT(11) NOT NULL ,
  `USERS_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `RFID_AUTHENTICATION_FKIndex1` (`USERS_ID` ASC) ,
  INDEX `RFID_AUTHENTICATION_FKIndex2` (`RFID_TAG_ID` ASC) ,
  CONSTRAINT `fk_{A6EB1914-11DD-4133-96A3-61550B77EB73}`
    FOREIGN KEY (`USERS_ID` )
    REFERENCES `Cerberus`.`USERS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{F5A69B10-3132-4778-8CD3-3A9622D55F73}`
    FOREIGN KEY (`RFID_TAG_ID` )
    REFERENCES `Cerberus`.`RFID_TAG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`CONSUMPTION_PROFILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`CONSUMPTION_PROFILE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`CONSUMPTION_PROFILE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `RFID_TAG_ID` INT(11) NOT NULL ,
  `AVERAGE_HOURLY_CONSUMPTION` INT(11) NULL ,
  `INSTANTANEOUS_CONSUMPTION` INT(11) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `CONSUMPTION_PROFILE_FKIndex1` (`RFID_TAG_ID` ASC) ,
  CONSTRAINT `fk_{2373581E-4EE3-407D-8B8A-CBE2D572DC28}`
    FOREIGN KEY (`RFID_TAG_ID` )
    REFERENCES `Cerberus`.`RFID_TAG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`GENERAL_PROFILE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`GENERAL_PROFILE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`GENERAL_PROFILE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `TYPE_OF_DEVICE` TINYTEXT NULL ,
  `CONSUMPTION_RANGE` INT(11) NULL ,
  `AVERAGE_HOURLY_CONSUMPTION` INT(11) NULL ,
  `INSTANTANEOUS_CONSUMPTION` INT(11) NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`CURRENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`CURRENT` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`CURRENT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `RFID_TAG_ID` INT(11) NOT NULL ,
  `USERS_ID` INT(11) NOT NULL ,
  `SOCKET_ID` INT(11) NOT NULL ,
  `TIMESTAMP` TIMESTAMP NULL ,
  `CURRENT` INT(11) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `CURRENT_FKIndex1` (`SOCKET_ID` ASC) ,
  INDEX `CURRENT_FKIndex2` (`USERS_ID` ASC) ,
  INDEX `CURRENT_FKIndex3` (`RFID_TAG_ID` ASC) ,
  CONSTRAINT `fk_{98F77DA9-88D3-44E2-809F-A02D07A0174E}`
    FOREIGN KEY (`SOCKET_ID` )
    REFERENCES `Cerberus`.`SOCKET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{620A4C79-2344-4454-B471-0E8D01FE0A66}`
    FOREIGN KEY (`USERS_ID` )
    REFERENCES `Cerberus`.`USERS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{01A8162B-8EAC-4B02-A493-867D7E7F7719}`
    FOREIGN KEY (`RFID_TAG_ID` )
    REFERENCES `Cerberus`.`RFID_TAG` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`CURRENT_HOUR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`CURRENT_HOUR` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`CURRENT_HOUR` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `USERS_ID` INT(11) NOT NULL ,
  `SOCKET_ID` INT(11) NOT NULL ,
  `TIMESTAMP` TIMESTAMP NULL ,
  `CURRENT_HOUR` INT(11) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `CURRENT_HOUR_FKIndex1` (`SOCKET_ID` ASC) ,
  INDEX `CURRENT_HOUR_FKIndex2` (`USERS_ID` ASC) ,
  CONSTRAINT `fk_{C7FD20AE-A7FE-48ED-8288-858441651AF2}`
    FOREIGN KEY (`SOCKET_ID` )
    REFERENCES `Cerberus`.`SOCKET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{F59B3C95-713E-45DB-AA76-F24A2D182DB1}`
    FOREIGN KEY (`USERS_ID` )
    REFERENCES `Cerberus`.`USERS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`EVENT` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`EVENT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `EVENT_NAME` TINYTEXT NULL ,
  `EVENT_DESCRIPTION` TINYTEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`CONNECTION_EVENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`CONNECTION_EVENT` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`CONNECTION_EVENT` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `OUTLET_ID` INT(11) NOT NULL ,
  `EVENT_ID` INT(11) NOT NULL ,
  `TIMESTAMP` TIMESTAMP NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `CONNECTION_EVENT_FKIndex1` (`EVENT_ID` ASC) ,
  INDEX `CONNECTION_EVENT_FKIndex2` (`OUTLET_ID` ASC) ,
  CONSTRAINT `fk_{3AD07AA9-3F08-406A-AA34-C28B9486A2BB}`
    FOREIGN KEY (`EVENT_ID` )
    REFERENCES `Cerberus`.`EVENT` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{0905D9E0-F215-41D3-9D86-75BC8BF3A8A4}`
    FOREIGN KEY (`OUTLET_ID` )
    REFERENCES `Cerberus`.`OUTLET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`RULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`RULE` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`RULE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NAME` TEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`TIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`TIP` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`TIP` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NAME` TEXT NULL ,
  PRIMARY KEY (`ID`) )
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`RULE_TIP_XREF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`RULE_TIP_XREF` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`RULE_TIP_XREF` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `TIP_ID` INT(11) NOT NULL ,
  `RULE_ID` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `TIPS_FKIndex1` (`RULE_ID` ASC) ,
  INDEX `TIPS_FKIndex2` (`TIP_ID` ASC) ,
  CONSTRAINT `fk_{98B92FAF-94B6-412E-840D-CAD887C4CD04}`
    FOREIGN KEY (`RULE_ID` )
    REFERENCES `Cerberus`.`RULE` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{441E7FCC-889E-45AA-B46E-B768C2F35E91}`
    FOREIGN KEY (`TIP_ID` )
    REFERENCES `Cerberus`.`TIP` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;


-- -----------------------------------------------------
-- Table `Cerberus`.`SYSTEM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cerberus`.`SYSTEM` ;

CREATE  TABLE IF NOT EXISTS `Cerberus`.`SYSTEM` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `OUTLET_ID` INT(11) NOT NULL ,
  `USERS_ID` INT(11) NOT NULL ,
  `NAME` TINYTEXT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `SYSTEM_FKIndex1` (`USERS_ID` ASC) ,
  INDEX `SYSTEM_FKIndex2` (`OUTLET_ID` ASC) ,
  CONSTRAINT `fk_{DBABFD7F-D1BC-49AC-A144-883A68EA2FA7}`
    FOREIGN KEY (`USERS_ID` )
    REFERENCES `Cerberus`.`USERS` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_{1DCA1623-B9EE-4ADE-B018-61A7DDA0D8FA}`
    FOREIGN KEY (`OUTLET_ID` )
    REFERENCES `Cerberus`.`OUTLET` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
PACK_KEYS = 0
ROW_FORMAT = DEFAULT;

USE `Cerberus` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
